---
- name: Create a unix group
  group:
    name: jira
    system: true
  notify: Restart jira service

- name: Create a unix user
  user:
    name: jira
    group: jira
    comment: JIRA system user
    shell: /bin/false
    home: /opt/atlassian-jira
    createhome: no
    system: true
  notify: Restart jira service

- name: Create data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: jira
    mode: 0770
  with_items:
    - /var/lib/jira
    - /var/log/jira
  notify: Restart jira service

- include_tasks: install.yml

- name: Create server.xml
  template:
    src: server.xml.j2
    dest: /opt/atlassian-jira-{{ jira_version }}/conf/server.xml
    owner: root
    group: root
    mode: 0644
  notify: Restart jira service

- name: Symlink logs directory
  file:
    path: /opt/atlassian-jira-{{ jira_version }}/logs
    state: link
    src: /var/log/jira
    force: true
    owner: root
    group: jira
  notify: Restart jira service

- name: Grant write privileges
  file:
    path: /opt/atlassian-jira-{{ jira_version }}/{{ item }}
    owner: root
    group: jira
    mode: 0775
  with_items:
    - conf
    - temp
    - webapps
    - work
  notify: Restart jira service

- name: Set home directory
  copy:
    dest: /opt/atlassian-jira-{{ jira_version }}/atlassian-jira/WEB-INF/classes/jira-application.properties
    content: "# Ansible managed - do not edit here!\njira.home=/var/lib/jira\n"
  notify: Restart jira service

- name: Set Java options
  copy:
    dest: /etc/default/jira
    content: "# Ansible managed - do not edit here!\nJAVA_OPTS='{{ jira_java_opts }}'\n"
  notify: Restart jira service

- include_tasks: postgresql.yml
  when: jira_configure_postgres

- name: Create systemd unit
  template:
    src: jira.service.j2
    dest: /etc/systemd/system/jira.service
    owner: root
    group: root
    mode: 0644
  register: unit
  notify:
    - Reload systemd configuration
    - Restart jira service

- meta: flush_handlers

- name: Enable and start
  systemd:
    name: jira.service
    state: started
    enabled: true
